MotChallenge2DBox
tracking
Traceback (most recent call last):
  File "/home/dan97494/Projekte/ThermalTrack/TrackEval/trackeval/eval.py", line 86, in evaluate
    res[curr_seq] = eval_sequence(curr_seq, dataset, tracker, class_list, metrics_list,
  File "/home/dan97494/Projekte/ThermalTrack/TrackEval/trackeval/_timing.py", line 17, in wrap
    result = f(*args, **kw)
  File "/home/dan97494/Projekte/ThermalTrack/TrackEval/trackeval/eval.py", line 242, in eval_sequence
    data = dataset.get_preprocessed_seq_data(raw_data, cls)
  File "/home/dan97494/Projekte/ThermalTrack/TrackEval/trackeval/_timing.py", line 17, in wrap
    result = f(*args, **kw)
  File "/home/dan97494/Projekte/ThermalTrack/TrackEval/trackeval/datasets/mot_challenge_2d_box.py", line 370, in get_preprocessed_seq_data
    to_remove_tracker = np.array([], np.int)
  File "/home/dan97494/miniconda3/envs/github_pbvs_challenge/lib/python3.8/site-packages/numpy/__init__.py", line 305, in __getattr__
    raise AttributeError(__former_attrs__[attr])
AttributeError: module 'numpy' has no attribute 'int'.
`np.int` was a deprecated alias for the builtin `int`. To avoid this error in existing code, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
The aliases was originally deprecated in NumPy 1.20; for more details and guidance see the original release note at:
    https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations





MotChallenge2DBox
tracking
Traceback (most recent call last):
  File "/home/dan97494/Projekte/ThermalTrack/TrackEval/trackeval/eval.py", line 86, in evaluate
    res[curr_seq] = eval_sequence(curr_seq, dataset, tracker, class_list, metrics_list,
  File "/home/dan97494/Projekte/ThermalTrack/TrackEval/trackeval/_timing.py", line 17, in wrap
    result = f(*args, **kw)
  File "/home/dan97494/Projekte/ThermalTrack/TrackEval/trackeval/eval.py", line 242, in eval_sequence
    data = dataset.get_preprocessed_seq_data(raw_data, cls)
  File "/home/dan97494/Projekte/ThermalTrack/TrackEval/trackeval/_timing.py", line 17, in wrap
    result = f(*args, **kw)
  File "/home/dan97494/Projekte/ThermalTrack/TrackEval/trackeval/datasets/mot_challenge_2d_box.py", line 370, in get_preprocessed_seq_data
    to_remove_tracker = np.array([], np.int)
  File "/home/dan97494/miniconda3/envs/github_pbvs_challenge/lib/python3.8/site-packages/numpy/__init__.py", line 305, in __getattr__
    raise AttributeError(__former_attrs__[attr])
AttributeError: module 'numpy' has no attribute 'int'.
`np.int` was a deprecated alias for the builtin `int`. To avoid this error in existing code, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
The aliases was originally deprecated in NumPy 1.20; for more details and guidance see the original release note at:
    https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations





